#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    poscount = 0
    negcount = 0
    zerocount = 0
    for i in range (0, n):
        if arr[i] > 0:
            poscount += 1
        elif arr[i] < 0:
            negcount += 1
        else:
            zerocount += 1
    pospor = poscount/ n
    negpor = negcount/ n
    zeropor = zerocount/ n
    print(pospor)
    print(negpor)
    print(zeropor)

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
