#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'staircase' function below.
#
# The function accepts INTEGER n as parameter.
#

def staircase(n):
    level = 1
    for i in range (1,n+1):
        for blank in range (n-level):
            print(' ', end='')
        for step in range (level):
            print('#', end='')
        print('')
        level += 1

if __name__ == '__main__':
    n = int(input().strip())

    staircase(n)
