#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    time_parts = s.split(':')
    hours = int(time_parts[0])
    minutes = int(time_parts[1])
    seconds = int(time_parts[2][:2])  
    period = time_parts[2][2:] 
    
    if period == 'PM' and hours < 12:
        hours += 12
    elif period == 'AM' and hours == 12:
        hours = 0
    
    answer = '{:02d}:{:02d}:{:02d}'.format(hours, minutes, seconds)
    
    return answer

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
